sudo: required
dist: trusty
language: node_js
node_js:
 - 6.9.4

branches:
  only:
   - master

addons:
apt:
  sources:
   - google-chrome
  packages:
   - google-chrome-stable

before_install:
 - export CHROME_BIN=google-chrome-stable
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

before_script:
 - npm install -g @angular/cli@1.0.0-beta.30
 - npm install -g angular-cli-ghpages
 - ng build --env=github --base-href "https://arturczopek.github.io/my-coach/"

cache:
  directories:
   - node_modules
   - $HOME/.nvm

script:
 - ng test --watch=false

after_success:
 - angular-cli-ghpages --no-silent --repo=https://GH_TOKEN@github.com/arturczopek/my-coach.git

env:
  global:
   - secure: "eUu+in86Dj0k0t9S+3/WTFQl6MxbUEVVU2xn906UhehmsIUlk5+dr7vc7jbvBhmAR9p2037k5rkz8Iywb0oLkHlmCYzV/kbF+OCPQ17s6DnKM+w56KI7M+rS3i+yqt/xxL8Z/d5qDjplZiZSl0r4EvZBwXzw41L0Xs2ypWBlL0JUiolrbGcvDd+O/hE4f3Cq79Tw/XAfVNxwh+cLe9a63ioNMDTDMdedRol6zwi0NiprAe0Nd0XXMFXXIi/hBiurE21IjhpBA2f+ipdV6HMxW+5Khk3uZwnwj7Jl0jqmGBidwsAK24btr/PotkEH+n1jiApTwrWV6+GQUwUaiJTs7ilIKCa5Hseki/ek/t9Sx2vdaFQcSmTc9iy5zOhqq34K3V8/ZvqKPdU4kZ59migbnIHgeaKC8mtIsU+EPqqO6hVZxRRA+VSvdnK8Ho36Bue2E45koxSOumv6C1Q1xOyajATBLYdVGQSLxg34N6sp3Ec8TMa+hxDs4BXvjNWhJD7FGplgFpCGP58YmNRt268zFr6wpwp2gQdt2i66wDVLy1i7C/n7En7IA02kd/d+3twtbt1diygPyNtGg5Aczrl1UyH0Wfhgn+K2O8orr+BzX6J6jQPFqWmP1cYNqp6lBu3SKszAZic2Id0z27x5x75u+Dz9RMJv9DE28CIjShV7NZI="


